#include<stdio.h>
int main(){
printf("Merhabalar \t \t (ilerlemek icin entera basiniz.)");
	getchar();
	printf("\n Sakincasi yoksa Isminizi ogrenebilir miyim?\n");
	char name [12];
	scanf("%s", &name);
	printf("\n Tekrardan hosgeldin %s \n",name);
	getchar();
	printf("\n Hayat nasil gidiyor bakalim ? %s \n",name);
	char asdas[15];
	scanf("%s", &asdas);
	getchar();
	printf("\n hayirlisi olsun yha \n");
	getchar();
	printf("\n Oyun oynamak ister misin? \t (eger istersen entera bas)");
	getchar();
	printf("\n haydi baslayalim o zaman %s \n %s hemen yanina bir telefon al hesap makinesini ac\t \t(actiysan entera bas)",&name,&name);
	getchar();
	printf("\n  sasirmaya hazir ol %s ve enterrrrrrrrrrr",&name);
	getchar();
	printf("\nSimdi senin zihnini okuyacagim ve ailen hakkinda bilgi verecegim\n Bunun icin 7 adimdan olusan islemleri\n sabirla yapman gerekiyor %s \n hazirsan baslayalim",&name);
	getchar();
	printf("\noncelikle hayatta olan erkek kardeslerinin sayisini ikiyle carp %s \n(eger erkek kardesin yhoksa 0 diye dusunerek isleme devam edebilirsin)\n (islemlerin her bittikten sonra entera basmayi unutma %s)",&name,&name);
	getchar();
	printf("\nsimdi bu sayiya 3 ekle %s",&name);
	getchar();
	printf("\nsimdi bu toplami 5 ile carp %s",&name);
	getchar();
	printf("\nsimdi de son sayiya kiz kardeslerinin sayisini ekle %s \t \t (eger kiz kardesin yhoksa 0 diye dusunerek isleme devam edebilirsin)",&name);
	getchar();
	printf("\nsimdi de son sayiyi 10 ile carp %s",&name);
	getchar();
	printf("\n ha gayret son iki islem %s\'cim",&name);
	getchar();
	printf("\n son sayiya su an hayatta olan cocugunun sayisini ekle %s",&name);
	getchar();
	printf("\n son olarak son elde ettigin sayidan 150 cikar %s",&name);
	getchar();
	printf("\n su anda bu elde ettigin sayiyi nasil kullanabilecegini mi dusunuyorsun? %s\'cim \n cok komiksin %s",&name,&name);
	getchar();
	printf("\n hemen soyleyeyim :)  %s\'cim",&name);
	getchar();
	printf("\n elde ettigin sayi uc haneli olmali degilmi?\n Lutfen bu elde ettigin sayinin birler basamagini gir:  ");
	int q;
	scanf("%d",&q);
	getchar();
	printf("\n Lutfen bu elde ettigin sayinin onlar basamagini gir:  ");
	int w;
	scanf("%d",&w);
	printf("\n Lutfen bu elde ettigin sayinin yuzler basamagini gir:  ");
	int e;
	scanf("%d",&e);
	printf("\n tum basamaklari girdigine gore heyecenlanmaya baslamalisin %s",&name);
	getchar();
	printf("\n Erkek kardes sayin : %d \n kiz kardes sayin : %d \n cocuklarinin sayisi : %d\n \n \n Dogru bildim mi? :)",e,w,q);
	getchar();
}